# Generated by Django 2.2.2 on 2019-06-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_movie_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('comedy', 'Comedy'), ('crime', 'Crime'), ('drama', 'Drama'), ('fantasy', 'Fantasy'), ('horror', 'Horror'), ('mystery', 'Mystery'), ('romance', 'Romance'), ('science fiction', 'Science Fiction'), ('social', 'Social'), ('thriller', 'Thriller'), ('urban', 'Urban'), ('western', 'Western')], default='action', max_length=50),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
