# Generated by Django 2.2.2 on 2019-06-09 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_auto_20190608_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
