# Generated by Django 2.2.2 on 2019-06-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0008_usertoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('detail', models.TextField(max_length=150)),
                ('genre', models.CharField(max_length=50)),
                ('original_language', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('country', models.CharField(max_length=50)),
            ],
        ),
    ]
