# Generated by Django 2.2.2 on 2019-06-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0009_moviesearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesearch',
            name='poster',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='movie_app/posters'),
        ),
    ]
