# Generated by Django 2.2.2 on 2019-06-14 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0013_moviesearch_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesearch',
            name='actor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_app.Actor'),
        ),
    ]
