# Generated by Django 2.2.2 on 2019-06-14 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0014_auto_20190614_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesearch',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.Actor'),
        ),
    ]
