# Generated by Django 2.2.2 on 2019-06-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0017_moviesearch_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesearch',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
